### ISSUE TITLE
Backward DFT missing normalization factor

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/codex-africanus#212] opened 2020-07-29 07:34 UTC
* Codex Africanus version: PerleyPolyhedron
* Python version: 3
* Operating System: Kubuntu 18.04

### Description

Backward DFT is missing normalization by number of contributing rows

### What I Did

```
        vis_dft = im_to_vis(mod[0,:,:].reshape(1,1,npix*npix).T.copy(), uvw, radec, frequency).repeat(2).reshape(nrow,1,2)   
        chanmap = np.array([0])
       
        detaper = kernels.compute_detaper(npix, np.outer(kernels.unpack_kernel(kern, W, OS), 
                                                         kernels.unpack_kernel(kern, W, OS)), W, OS)
        nterm = np.sqrt(1 - radec[:,0]**2 - radec[:,1]**2).reshape((npix, npix))
        vis_grid = gridder.gridder(uvw,
                                   vis_dft,
                                   wavelength,
                                   chanmap,
                                   npix,
                                   cell * 3600.0,
                                   (0, np.pi/4.0),
                                   (0, np.pi/4.0),
                                   kern,
                                   W,
                                   OS,
                                   "None", # no faceting
                                   "None", # no faceting
                                   "I_FROM_XXYY",
                                   "conv_1d_axisymmetric_packed_scatter",
                                   do_normalize=True)
        ftvis = (np.fft.fftshift(np.fft.ifft2(np.fft.ifftshift(vis_grid[0,:,:]))).reshape((1, npix, npix)) / detaper / nterm).real * npix ** 2 
        dftvis = vis_to_im(vis_dft, uvw, radec, frequency, np.zeros(vis_dft.shape, dtype=np.bool)).T.copy().reshape(2,1,npix,npix) / nterm / nrow
```
This brings the end result closer to alignment (star pattern of unity delta functions being predicted)

![image](https://user-images.githubusercontent.com/7934586/88768342-3e9ed280-d17b-11ea-945a-b3e41f7a4547.png)

**Comment by sjperkins** [comment] 2020-07-29 07:51
I think this is by design? From here: https://codex-africanus.readthedocs.io/en/latest/dft-api.html

> This is implemented by the vis_to_im() function. Note that an imaging algorithm using these operators will actually reconstruct I/n but that it is trivial to obtain I since n is known at each location in the image.

/cc @landmanbester

**Comment by bennahugo** [comment] 2020-07-29 07:55
no: it is missing 1/N sumsum .... where N is number of rows as I indicated. I know it doesn't have the n term normalization included

**Comment by landmanbester** [comment] 2020-07-29 08:16
Well, this is just a question of normalisation. There is no wsum in the definition of the DFT is there? Normalising by wsum would ruin the adjointness of the operators unless we normalise by sqrt(wsum) both ways but I don't really want to do that. Maybe we should drop the DFT in its current form and change it to an explicit gridder rather. It's only really useful for predicting visibilities of point sources and we have that functionality in the RIME predict anyway. Let's discuss this at the next imaging meeting.

@bennahugo I don't understand why there is such a big difference between the DFT and your gridder. Is it the w-term? Also, why are you passing in radec and not lm?

**Comment by bennahugo** [comment] 2020-07-29 09:11
it is not weight sums @landmanbester. The correct DFT formula is given in SI II:
![image](https://user-images.githubusercontent.com/7934586/88780779-c68cd880-d18b-11ea-949e-231ce52ffdef.png)
Note the missing M term.

Currently the DFT response to a visibilities from unity sources is not unity due to this bug.

I'm using a very small field of view so radec is a reasonable approximation. I think it is the detapering. I'm still playing around with the detapering kernel.

**Comment by landmanbester** [comment] 2020-07-29 09:23
I disagree, that is not the definition of the DFT and it is not a bug its a feature. The normalisation factor, which is wsum and not nrow if the weights are not unity, just puts the dirty image in units of Jy/beam. Look at the test cases @bennahugo 

https://github.com/ska-sa/codex-africanus/blob/master/africanus/dft/tests/test_dft.py

I have checked the forward operator against the FFT and then checked the adjointness so there is no problem except one of definition, which is given in the docs. This is not an explicit gridder. I think that is the assumption you are working on

**Comment by bennahugo** [comment] 2020-07-29 09:28
Ok I will code an alternative definition up according to the synthesis imaging definition for a direct fourier transform because it is the one I need to compare against.

**Comment by sjperkins** [comment] 2020-07-31 15:34
Thanks all, I'm going to close this issue.

**Closed by sjperkins** 2020-07-31 15:34 UTC
